# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#


version: 2.1

orbs:
  slack: circleci/slack@3.4.2

executors:
  shopizer-ci:
    docker:
      - image: etienneturin/citest:latest
        auth:
          username: etienneturin
          password: fefcf6bf-b1be-4e9c-906b-2d709a1bc174

working_directory: /tmp


# Define the jobs we want to run for this project
jobs:

  build:
    executor: shopizer-ci
    steps:
      - checkout
      - run: echo "shopizer build and test"
      #- run:
      #    name: Run shell script
      #    command: |
      #      chmod +x ./mvnw
      #      set -x
      #      /home/shopizer/tools/shopizer.sh tests
      - persist_to_workspace:
          root: .
          paths:
            - sm-shop/*

  deploy:
    machine: true
    steps:
      - attach_workspace:
          at: .
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: |
          ls -al
      - run: |
          docker login -u etienneturin -p fefcf6bf-b1be-4e9c-906b-2d709a1bc174
      - run: |
          (cd sm-shop && docker build . -t etienneturin/shopizertest:latest)
      - run: |
          docker push etienneturin/shopizertest:latest


# Orchestrate our job run sequence
workflows:
  builds_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
